### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by franklinyu** [nspec/NSpec.VsAdapter#10]
Currently I cannot install in on Visual Studio 2017: double-clicking the VSIX file (when Visual Studio is not running) gives me

![error](https://user-images.githubusercontent.com/3153452/30083879-2b4a589e-925e-11e7-8d9b-b606133aa56e.png)

and the install log is

```text
9/5/2017 5:09:07 PM - Microsoft VSIX Installer
9/5/2017 5:09:08 PM - -------------------------------------------
9/5/2017 5:09:08 PM - vsixinstaller.exe version:
9/5/2017 5:09:08 PM - 15.0.396+gef04a54a6a
9/5/2017 5:09:08 PM - -------------------------------------------
9/5/2017 5:09:08 PM - Command line parameters:
9/5/2017 5:09:08 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\zlyu\Downloads\NSpec.VsAdapter.vsix
9/5/2017 5:09:08 PM - -------------------------------------------
9/5/2017 5:09:08 PM - Microsoft VSIX Installer
9/5/2017 5:09:08 PM - -------------------------------------------
9/5/2017 5:09:08 PM - Initializing Install...
9/5/2017 5:09:08 PM - Extension Details...
9/5/2017 5:09:08 PM - 	Identifier         : BrainCrumbz.NSpec.VsAdapter
9/5/2017 5:09:08 PM - 	Name               : NSpec VS Adapter
9/5/2017 5:09:08 PM - 	Author             : BrainCrumbz
9/5/2017 5:09:08 PM - 	Version            : 1.0.0
9/5/2017 5:09:08 PM - 	Description        : A test adapter to run NSpec tests from Test Explorer window in Visual Studio 2013 and later.
9/5/2017 5:09:08 PM - 	Locale             : en-US
9/5/2017 5:09:08 PM - 	MoreInfoURL        : https://github.com/nspec/NSpec.VsAdapter
9/5/2017 5:09:08 PM - 	InstalledByMSI     : False
9/5/2017 5:09:08 PM - 	SupportedFrameworkVersionRange : [4.5,)
9/5/2017 5:09:08 PM - 
9/5/2017 5:09:08 PM - 	SignatureState     : Unsigned
9/5/2017 5:09:08 PM - 	Supported Products : 
9/5/2017 5:09:08 PM - 		Microsoft.VisualStudio.Pro
9/5/2017 5:09:08 PM - 			Version : [12.0,14.0]
9/5/2017 5:09:08 PM - 
9/5/2017 5:09:08 PM - 	References         : 
9/5/2017 5:09:08 PM - Signature Details...
9/5/2017 5:09:08 PM - 	Extension is not signed.
9/5/2017 5:09:08 PM - 
9/5/2017 5:09:08 PM - Searching for applicable products...
9/5/2017 5:09:08 PM - Found installed product - Global Location
9/5/2017 5:09:08 PM - Found installed product - Visual Studio Community 2017
9/5/2017 5:09:08 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

This looks similar to #2.

**Comment by BrainCrumbz** [comment]
I think this project readme is generating confusion and it may be a good time to fix that.

As a VSIX extension, it is available under VS2013 and VS2015. It is not yet available under VS 2017, as an extension.

But VS 2017 adds another mean to add test adapters to a solution: add it as a NuGet package to one of included projects. So that IDE is covered too, thanks to the NuGet package.

For a working setup, please have a look at [examples/NetFrameworkSample](https://github.com/nspec/NSpec.VsAdapter/tree/master/examples/NetFrameworkSample) solution, specifically at test project's [packages.config](https://github.com/nspec/NSpec.VsAdapter/blob/356db47d1a5f6aca9d6903b5de9c031b16943d4c/examples/NetFrameworkSample/test/LibrarySpecs/packages.config#L6): `<package id="NSpec.VsAdapter" version="1.0.0" targetFramework="net452" developmentDependency="true" />`.

Again, just remember that this Adapter at the moment only works for classic .NET framework projects, not .NET Core ones.

**Comment by BrainCrumbz** [comment]
For the records: we updated readme description.  
For unrelated reasons (change of publisher) we also are in the process of temporarily removing the extension from marketplace and adding it again under a new publisher and/or ID.
